### ISSUE TITLE
Doesn't handle meta tags

### ISSUE THREAD

**Issue by krainboltgreene** [meh/paggio#3]
``` ruby
html! do
  meta charset: "utf-8"
end
```

``` html
<head>
	<meta charset="utf-8">
	</meta>
</head>
```

**Comment by meh** [comment]
Fixed on master.

**Comment by krainboltgreene** [comment]
That technically works, but in reality if any element has no content (even a `p` tag) it's not allowed to have a closing element. Meta and others aren't "special", they just never have content.

**Comment by krainboltgreene** [comment]
Ignore me, the mozilla documentation seems to be out of sync with the real w3 spec.

**Comment by meh** [comment]
Yeah, I checked, they're categorized as void elements and it's only for them :panda_face:
